export const GET_ANIMALS = "GET_ANIMALS";
export const EDIT_ANIMAL_SUCCESS = "EDIT_ANIMAL_SUCCESS";
export const EDIT_ANIMAL_ERROR = "EDIT_ANIMAL_ERROR";
export const CREATE_ANIMAL_SUCCESS = "CREATE_ANIMAL_SUCCESS";
export const CREATE_ANIMAL_ERROR = "CREATE_ANIMAL_ERROR";
export const DELETE_ANIMAL_SUCCESS = "DELETE_ANIMAL_SUCCESS";
export const DELETE_ANIMAL_ERROR = "DELETE_ANIMAL_ERROR";