export const GET_SHELTERS = "GET_SHELTERS";
export const EDIT_SHELTER_SUCCESS = "EDIT_SHELTER_SUCCESS";
export const EDIT_SHELTER_ERROR = "EDIT_SHELTER_ERROR";
export const CREATE_SHELTER_SUCCESS = "CREATE_SHELTER_SUCCESS";
export const CREATE_SHELTER_ERROR = "CREATE_SHELTER_ERROR";
export const DELETE_SHELTER_SUCCESS = "DELETE_SHELTER_SUCCESS";
export const DELETE_SHELTER_ERROR = "DELETE_SHELTER_ERROR";