export const GET_WALKS = "GET_WALKS";
export const EDIT_WALK_SUCCESS = "EDIT_WALK_SUCCESS";
export const EDIT_WALK_ERROR = "EDIT_WALK_ERROR";
export const CREATE_WALK_SUCCESS = "CREATE_WALK_SUCCESS";
export const CREATE_WALK_ERROR = "CREATE_WALK_ERROR";
export const DELETE_WALK_SUCCESS = "DELETE_WALK_SUCCESS";
export const DELETE_WALK_ERROR = "DELETE_WALK_ERROR";